package me.staff4.GringottsTool.MessageHadler;

public enum MessageCommand {
    ID, VERSION, START, HELP, SEARCH, STATUS, DEBTS, CARDS, RULES,
    ABOUTME, ABOUTMYPAYMENTS, DUCKLIST, PROXY, FAST, QUEUE, CREDITHISTORY,
    CREDITHISTORYFULL, FULLSEARCH, LOAN, SENDTOALL, NEW_LOAN, TODAY_DEBTORS, POLL, OVERDUE_DEBTORS
}
