variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  MAVEN_IMAGE: maven:3.8.5-openjdk-17-slim

services:
  - docker:20.10.16-dind

stages:
  - build
  - deploy

build-jar:
  stage: build
  image: "$MAVEN_IMAGE"
  when: manual
  script:
    - mvn clean package -DskipTests

unit-test:
  stage: build
  image: "$MAVEN_IMAGE"
  when: manual
  allow_failure: true
  script:
    - mvn test

build-docker:
  stage: build
  when: manual
  script:
    - echo "$D_PASSWORD" | docker login -u "$D_USER" --password-stdin registry-1.docker.io
    - docker build -t tut0r/gringottstool:latest .
    # - docker build -t tut0r/gringottstool:"$CI_COMMIT_SHORT_SHA" .
    # - docker push tut0r/gringottstool:"$CI_COMMIT_SHORT_SHA"
    - docker push tut0r/gringottstool:latest

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
